[SERVICE]
    Flush      5
    Daemon     Off
    Log_Level  info

[INPUT]
    Name             tail
    Alias            error_tail
    Path             /var/log/starman/error.log
    Tag              error
    Read_from_Head   true
    Refresh_Interval 5

[OUTPUT]
    Name        loki
    Match       error
    Host        logs-prod-042.grafana.net
    Port        443
    tls         On
    tls.verify  On
    Http_User   ${LOKI_USER}
    Http_Passwd ${LOKI_PASSWORD}
    Labels      source=dreamwidth, service=${DW_LOKI_SERVICE}, stream=error
    line_format key_value
